/*
MIT License

Copyright (c) 2024 Robert M Pavey

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// List published in this document:
// https://fanningfamilyhistory.com/wp-content/uploads/eBook-Placenames-Abbreviations-13-June-2011.pdf
const vicbdmPlaceAbbreviationTable = {
  "A P": "Albert Park",
  "A PARK": "Albert Park",
  "A PK": "Albert Park",
  "A V": "Ascot Vale",
  "A VALE": "Ascot Vale",
  AARA: "Ararat",
  AB: "Abbotsford",
  ABB: "Abbotsford",
  ABBFORD: "Abbotsford",
  ABBO: "Abbotsford",
  ABBY: "Abbyard",
  ABER: "Aberdeen",
  ABER: "Aberfeldy (Sale District)",
  "ABERDEEN NB": "Aberdeen Scotland",
  ABERDEENSH: "Aberdeenshire Scotland",
  ABIN: "Abingdon",
  "ABT'FORD": "Abbotsford",
  ABTON: "Ashburton",
  ACHE: "Acheron",
  ACHE: "Acheron River",
  "AD LD": "Adelaide Lead",
  ADALE: "Armadale",
  ADDGTON: "Addington",
  ADDI: "Addington",
  ADE: "Adelaide South Australia",
  ADEL: "Adelaide South Australia",
  "ADELA LEAD": "Adelaide Lead",
  "ADELAD LD": "Adelaide Lead",
  ADRA: "Alexandra",
  "A'FORD": "Allansford",
  AFR: "Africa",
  AFRI: "Africa",
  AFRIC: "Africa",
  AHEARST: "Amherst",
  AHME: "Amherst",
  AHURST: "Amherst",
  AILS: "Ailsa",
  AIT: "Aitkens Gap",
  AIT: "Mt Aitken",
  AITK: "Aitkens Gap",
  AITK: "Mt Aitken",
  "AL LA": "Allans Flat",
  ALB: "Alberton",
  "ALB PARK": "Albert Park",
  ALBE: "Alberton",
  ALBER: "Alberton",
  ALBERT: "Alberton",
  ALBI: "Albion",
  ALBU: "Albury",
  ALEX: "Alexandra",
  ALFR: "Alfredton",
  ALLA: "Allans Flat",
  ALLE: "Allendale",
  ALLEN: "Allendale",
  "ALMA DGS": "Alma Diggings",
  ALPH: "Alphington",
  ALPHTON: "Alphington",
  "AM PH": "Amphitheatre",
  AMER: "America",
  AMHE: "Amherst",
  AMPHITHRE: "Amphitheatre",
  AMS: "Amsterdam Holland",
  AMST: "Amsterdam Holland",
  "AN DE": "Andersons Creek",
  ANAK: "Anakie",
  ANAK: "Anakie Hill",
  ANAK: "Anakies",
  ANDE: "Andersons Creek",
  "ANDSON C": "Andersons Creek",
  ANGL: "Anglesey Wales",
  ANTR: "County Antrim Ireland",
  ANTW: "Antwerp",
  ANTW: "Antwerp Belgium",
  APHI: "Amphitheatre",
  APOL: "Apollo Bay",
  "APOLLO B": "Apollo Bay",
  APPO: "Apollo Bay",
  APSE: "Apsley",
  "AR DALE": "Armadale",
  "AR RA": "Ararat",
  ARAR: "Ararat",
  "ARARAT ASY": "Ararat Asylum",
  ARAT: "Ararat",
  ARCA: "Arcadia",
  ARDALE: "Armadale",
  ARDO: "Ardochy",
  ARDTON: "Ardgarton",
  ARGY: "Argyll Scotland",
  ARIN: "Aringa",
  ARMA: "Armadale",
  ARMS: "Armstrongs Diggings",
  "ARMSTG DG": "Armstrongs Diggings",
  ARRA: "Ararat",
  "ARTHURS SE": "Arthurs Seat",
  "ARTHURS ST": "Arthurs Seat",
  ARUN: "Arundel",
  "AS VALE": "Ascot Vale",
  ASCO: "Ascot (2)",
  ASCO: "Ascot Vale",
  ASH: "Ashby",
  ASHB: "Ashby",
  AUBU: "Auburn",
  AUDL: "Audley",
  "AV EN": "Avenel",
  AVE: "Avenel",
  AVEN: "Avenel",
  AVO: "Avoca",
  AVOC: "Avoca",
  "AVOCA DGS": "Avoca Diggings",
  "AVOCA DIGG": "Avoca Diggings",
  "AX ED": "Axedale",
  AXED: "Axedale",
  "B ARAT": "Ballarat",
  "B FAST": "Belfast",
  "B HILL": "Box Hill",
  "B MARSH": "Bacchus Marsh",
  "B MEADOWS": "Broadmeadows",
  "B MSH": "Bacchus Marsh",
  "B WARTHA": "Barnawartha",
  "B WICK": "Brunswick",
  "B WOOD": "Burwood",
  "B WORTH": "Beechworth",
  "B YONG": "Buninyong",
  "BA IR": "Bairnsdale",
  "BA LM": "Balmoral",
  "BA RK": "Barker's Creek (2)",
  "BA RK": "Barkly",
  "BA RK": "Barkstead",
  "BA RN": "Barnawartha",
  BAC: "Bacchus Marsh",
  BACC: "Bacchus Marsh",
  BACK: "Back Creek (6)",
  BADA: "Badaginnie",
  BAG: "Bagshot",
  BAGS: "Bagshot",
  BAIL: "Baillieston",
  BAILLIESTO: "Baillieston",
  BAIR: "Bairnsdale",
  BALA: "Balaclava",
  BALAC: "Balaclava",
  BALD: "Bald Hill (4)",
  BALL: "Ballan",
  BALL: "Ballarat",
  "BALL E": "Ballarat East",
  BALLT: "Ballarat",
  "BALLT E": "Ballarat East",
  "BALLT EAST": "Ballarat East",
  BALLYASSY: "Ballyshanassy",
  BALLYSHANA: "Ballyshanassy",
  BALLYSHANN: "Ballyshanassy",
  BALM: "Balmoral",
  BALN: "Balnarring",
  BALNAING: "Balnarring",
  BALW: "Balwyn",
  BANY: "Banyena",
  BANY: "Banyenong",
  BAR: "Barker's Creek (2)",
  BAR: "Barkly",
  BARB: "Barber's Creek",
  BARF: "Barfold",
  BARI: "Baringhup",
  BARK: "Barker's Creek (2)",
  BARK: "Barkly",
  BARK: "Barkstead",
  BARN: "Barnawartha",
  BARNATHA: "Barnawartha",
  BARNTHA: "Barnawartha",
  BARR: "Barrabool",
  BARR: "Barrapoort",
  "BARRYS R": "Barry's Reef",
  "BARRYS REE": "Barry's Reef",
  "BARRYS RF": "Barry's Reef",
  BARWO: "Barwon Heads",
  BARWO: "Barwon River",
  BASS: "Bass River",
  BATE: "Batesford",
  BATM: "Batman's Swamp",
  BAYL: "Bayles",
  BAYN: "Baynton",
  BBEET: "Burrumbeep",
  BBEET: "Burrumbeet",
  BBURN: "Blackburn",
  BDALE: "Bairnsdale",
  BDARA: "Boroondara",
  "BE EC": "Beechworth",
  "BE LF": "Belfast",
  "BE LL": "Bellarine",
  "BE NA": "Benalla",
  "BE RW": "Berwick (2)",
  BEACH: "Beechworth",
  BEAL: "Bealiba",
  BEAU: "Beaufort",
  BECK: "Beckworth",
  BECK: "Mount Beckworth",
  BEEA: "Beeac",
  BEEC: "Beechworth",
  BELF: "Belfast",
  BELL: "Bellarine",
  BELLA: "Bellarine",
  BELM: "Belmont",
  BELV: "Belvoir",
  BEN: "Benalla",
  BENA: "Benalla",
  BEND: "Bendigo",
  BEND: "Bendoc",
  BENT: "Bentleigh",
  BERE: "Berembroke",
  BERM: "Bermondsey",
  BERM: "Bermuda",
  BERW: "Berwick (2)",
  BET: "Bet-Bet",
  BETB: "Bet-Bet",
  BETH: "Bethanga",
  BEVE: "Beveridge",
  BFORD: "Batesford",
  BFORD: "Beauford",
  BFORD: "Broadford",
  BFORT: "Beaufort",
  BGEICH: "Ballangeich",
  BGO: "Bendigo",
  BHEAD: "Barwon Heads",
  BHOLME: "Branxholme",
  BIGH: "Big Hill",
  BIGR: "Big River",
  BIND: "Bindi Cr or Mount",
  BINDI: "Bindi Cr or Mount",
  BINE: "Bellarine",
  "B'INE": "Bellarine",
  BIRC: "Birch's Hill or Creek",
  BIRM: "Birmingham",
  BIRR: "Birregurra",
  "BK SWAMP": "Black Swamp",
  "BL AC": "Blackwood",
  BLAC: "Black Station",
  BLAC: "Blackwood",
  "BLACK L": "Black Lead",
  "BLACK DG C": "Black Dog Creek",
  "BLACK F": "Black Forest",
  "BLACK FOR": "Black Forest",
  "BLACK FRST": "Black Forest",
  "BLACK FT": "Black Forest",
  "BLACK GY": "Black Gully Creek",
  "BLACK H": "Black Hill (3)",
  "BLACK LD": "Black Lead",
  "BLACK SPRG": "Black Springs",
  "BLACK SWMP": "Black Swamp",
  BLACKFELLO: "Blackfellow Creek",
  BLAK: "Blakeville",
  BLAN: "Blanket Flat",
  BLAND: "Buckland",
  BLEAK: "Bleak House",
  "BLK DOG CK": "Black Dog Creek",
  BLUE: "Blue Mountain",
  BLUE: "Blue Mountains",
  "BLUE MT": "Blue Mountain",
  "BLUE MTN": "Blue Mountain",
  "BLUE MTS": "Blue Mountains",
  BMDOWS: "Broadmeadows",
  BMORAL: "Balmoral",
  "BO GG": "Boggy Creek (4)",
  "BO LI": "Bolinda",
  BOCH: "Bochara",
  BOGG: "Boggy Creek (4)",
  BOGO: "Bogong",
  BOLA: "Bolac",
  BOLI: "Bolinda",
  BOLW: "Bolwarra",
  BOONDARA: "Boroondara",
  BOONDARRA: "Boroondara",
  BOOR: "Boort",
  BOOR: "Boroondara",
  BORO: "Boronia",
  BORO: "Boroondara",
  BOST: "Boston USA or England",
  BOUL: "Boulogne France",
  BOWM: "Bowman's Forest",
  BOXF: "Box Forest",
  BOXH: "Box Hill",
  "BR OO": "Broomfield",
  BRAN: "Brandy Creek",
  BRANXH: "Branxholme",
  BRAT: "Ballarat",
  BRAY: "Braybrook",
  BREA: "Break O' Day",
  BREA: "Breakwater",
  "BREAK O DA": "Break O' Day",
  "BREK ODA": "Break O' Day",
  BRIA: "Briagalong",
  BRID: "Bridgewater",
  BRIG: "Bright",
  BRIG: "Brighton",
  BRINE: "Bellarine",
  BRIS: "Brisbane Queensland",
  BROA: "Broadford",
  BROK: "Broken River",
  BROO: "Broomfield",
  BROOM: "Broomfield",
  BROW: "Brown's Diggings",
  BROW: "Brownsdale",
  "BROWN D": "Brown's Diggings",
  BROWNS: "Brown's Diggings",
  BRRAH: "Bolworrah",
  BRSWCK: "Brunswick",
  BRTN: "Brighton",
  BRTN: "Britain",
  BRUC: "Bruce's Creek",
  BRUN: "Brunswick",
  BRUNS: "Brunswick",
  BRUS: "Brussels Belgium",
  BRUT: "Bruthen",
  BSTEAD: "Barkstead",
  BTON: "Brighton",
  "BU NG": "Bungaree",
  "BU NI": "Buninyong",
  BUAN: "Buangor",
  BUCH: "Buchan",
  BUCK: "Buckland",
  BULL: "Bull Dog",
  BULL: "Bulla",
  BULL: "Bulleen",
  BULL: "Bullengarook",
  BULL: "Bullock Creek",
  "BULLA and TU": "Bulla and Tullarmarine",
  "BULLA BUL": "Bulla Bulla",
  "BULLA BULL": "Bulla Bulla",
  "BULLA TULL": "Bulla and Tullarmarine",
  BULLAR: "Bullarook",
  BULLARO: "Bullarook",
  BULLAROO: "Bullarook",
  BULLENGARO: "Bullengarook",
  BULN: "Buln-Buln",
  BUND: "Bunding",
  BUND: "Bundoora",
  BUNDA: "Bundalong",
  BUNG: "Bungaree",
  BUNG: "Bung-Bong",
  BUNG: "Bungeeluke",
  BUNG: "Bunguluke",
  BUNI: "Buninyong",
  BUNTINGDAL: "Buntingdale Creek",
  BURK: "Burke's Flat",
  BURN: "Burnt Creek (4)",
  "BURNT BDGE": "Burnt Bridge",
  "BURNT CREE": "Burnt Creek (4)",
  BURR: "Burrumbeep",
  BURR: "Burrumbeet",
  BURW: "Burwood",
  BUSH: "Bush Station",
  BUSH: "Bushfield",
  BUSH: "Bushy Creek",
  BWATHA: "Barnawartha",
  BWK: "Brunswick",
  BWOOD: "Burwood",
  BWORTH: "Beechworth",
  BYAD: "Byaduc",
  BYAW: "Byawatha",
  BYLA: "Bylands",
  BYONG: "Buninyong",
  "C BELL FLD": "Campbellfield",
  "C CA": "County Caven Ireland",
  "C CL": "County Clare Ireland",
  "C GA": "County Galway Ireland",
  "C HILL": "Clifton Hill",
  "C LI": "County Limerick or Limerick City",
  "C OTWAY": "Cape Otway",
  "C SCHANCK": "Cape Schanck",
  "C SPR": "Clifton Springs",
  "C WARRE": "Connewarre",
  "C WICK": "County Wicklow Ireland",
  "CA RA": "Caramut",
  "CA RO": "Corop",
  CALE: "Caledonia Cr/Gu/Reef",
  CALEDDIG: "Caledonia Diggings",
  "CALEDN DG": "Caledonia Diggings",
  "CALEDON DG": "Caledonia Diggings",
  CALF: "California Gully",
  "CALFN GY": "California Gully",
  "CALFNIA GY": "California Gully",
  "CALFORN G": "California Gully",
  CALL: "Callawadda",
  CALL: "Callen Ireland",
  CAMB: "Cambrian Hill",
  CAMBELLFIE: "Campbellfield",
  CAMBFLD: "Campbellfield",
  "CAMBN HIL": "Cambrian Hill",
  "CAMBR HILL": "Cambrian Hill",
  CAMP: "Camp Hill",
  CAMP: "Campaspe",
  CAMP: "Campbellfield",
  CAMP: "Campbells Creek (2)",
  CAMP: "Camperdown",
  CAMPASP: "Campaspe",
  CAMPB: "Campbells Creek (2)",
  "CAMPB CK": "Campbells Creek (2)",
  CAMPBELLS: "Campbells Creek (2)",
  CAMPBELLT: "Campbell Town",
  CAMPBELLTN: "Campbell Town",
  CAMPBELLTP: "Campbell Town",
  CAMPBFD: "Campbellfield",
  "CAMPBLLS C": "Campbells Creek (2)",
  CAMPDOWN: "Camperdown",
  CANA: "Canada",
  CANN: "Cannum",
  CANT: "Canton China",
  "CAPE CLEA": "Cape Clear",
  "CAPE PATTE": "Cape Patterson",
  CARA: "Caramut",
  CARD: "Cardiff (Wales)",
  CARD: "Cardigan",
  CARDIGANSH: "Cardiganshire Wales",
  CARDIGSH: "Cardiganshire Wales",
  CARG: "Cargarie",
  CARI: "Carisbrook",
  CARL: "Carlton",
  CARL: "Carlsruhe",
  CARLHE: "Carlsruhe",
  CARLO: "County Carlow Ireland",
  CARLRUH: "Carlsruhe",
  CARLSRUE: "Carlsruhe",
  CARLT: "Carlton",
  CARLY: "Carlyle",
  CARM: "Carmarthenshire Wales",
  CARN: "Carngham",
  CARNG: "Carngham",
  CARNGH: "Carngham",
  CARR: "Carrapooce",
  CARRALUP: "Carralulup",
  CAS: "Castlemaine",
  CASH: "Cashel",
  CASH: "Cashel Co Tipperary Ireland",
  CAST: "Casterton",
  CAST: "Castlemaine",
  CAST: "Castlemaine Co Kerry Ireland",
  CASTER: "Casterton",
  CASTLEMNE: "Castlemaine",
  CASTLMA: "Castlemaine",
  CASTMA: "Castlemaine",
  CASTMAINE: "Castlemaine",
  CASTON: "Casterton",
  CASTTON: "Casterton",
  CATH: "Cathcart",
  CATT: "Cattle Station",
  CAUL: "Caulfield",
  CAULD: "Caulfield",
  CAVA: "County Caven Ireland",
  CAVAN: "County Caven Ireland",
  CAVE: "Cavendish",
  "CB FIELD": "Campbellfield",
  "CBELLS C": "Campbells Creek (2)",
  CBOURNE: "Cranbourne",
  CBROOK: "Carisbrook",
  CBROOK: "Colebrook",
  CDOWN: "Camperdown",
  CERE: "Ceres",
  "C'FIELD": "Caulfield",
  "CH AR": "Charlton (2)",
  CHAM: "Cheltenham",
  CHAP: "Chapel Hill",
  CHAR: "Charlotte Plains",
  CHAR: "Charlton (2)",
  CHAT: "Chatham Kent England",
  CHAT: "Chatsworth",
  CHATSWTH: "Chatsworth",
  CHEL: "Cheltenham",
  CHELTAM: "Cheltenham",
  CHELTNM: "Cheltenham",
  CHEP: "Chepstow",
  CHER: "Cherry Tree",
  "CHERRY TRE": "Cherry Tree",
  CHET: "Chetwynd",
  CHEW: "Chewton",
  CHIL: "Chiltern",
  CHIL: "Chilwell (Geelong)",
  CHILTE: "Chiltern",
  CHILTEN: "Chiltern",
  CHILTER: "Chiltern",
  CHIN: "China",
  CHIN: "Chintin",
  "CHINAS FL,": "Chinaman's Flat",
  CHINEMANS: "Chinaman's Flat",
  "CHINMN FL": "Chinaman's Flat",
  "CL UN": "Clunes",
  CLA: "County Clare Ireland",
  CLANDS: "Crowlands",
  CLAR: "Clarendon",
  CLAR: "County Clare Ireland",
  CLARE: "County Clare Ireland",
  CLAY: "Clayton",
  CLEA: "Clear Lake",
  CLIF: "Clifton Hill",
  CLIFTN: "Clifton Springs",
  CLON: "Clonmel County Tipperary",
  CLONMEL: "Clonmel County Tipperary",
  CLOW: "Clowe's Forest",
  "CLOWES FT": "Clowe's Forest",
  CLUN: "Clunes",
  CLYD: "Clyde",
  CLYD: "Clyde Bank",
  CLYD: "Clydesdale",
  CMAINE: "Castlemaine",
  "CO GH": "Coghills Creek",
  "CO LA": "Colac",
  "CO LL": "Collingwood",
  "CO RO": "Corop",
  COBB: "Cobbler's Gully",
  COBD: "Cobden",
  COBR: "Cobram",
  COBU: "Coburg",
  COCH: "Cochrane's Diggings",
  COCHRAN: "Cochrane's Diggings",
  COCHRANE: "Cochrane's Diggings",
  "COCHRNS DG": "Cochrane's Diggings",
  COCK: "Cockatoo Creek (2)",
  COCK: "Cockpen",
  CODGTON: "Codrington",
  CODR: "Codrington",
  COGH: "Coghills Creek",
  COGHILLSCK: "Coghills Creek",
  COHU: "Cohuna",
  COIM: "Coimadai",
  COLA: "Colac",
  COLB: "Colbinabbin",
  COLE: "Coleraine",
  COLER: "Coleraine",
  COLI: "Coliban Diggings",
  COLL: "Collingwood",
  COLLINGWD: "Collingwood",
  COLLWOOD: "Collingwood",
  COLO: "Cologne Germany",
  COMM: "Commissioners' Gully",
  COMMGLY: "Commissioners' Gully",
  "COMMRS GLY": "Commissioners' Gully",
  "COMMS GLY": "Commissioners' Gully",
  COMO: "Coomoora",
  "CONCLLA C": "Concongela Creek",
  CONCONGE: "Concongela Creek",
  CONCONGELL: "Concongela Creek",
  COND: "Condah",
  CONN: "Connewarre",
  CONNE: "Connewarre",
  CONO: "Conover",
  COOM: "Coomoora",
  COON: "Coongulmerang",
  COOR: "Lake Coorong",
  COPE: "Copenhagen Denmark",
  COR: "County Cork Ire or Cork City",
  CORA: "Corack",
  CORD: "Corduroy",
  CORI: "Corinella",
  CORI: "Corio",
  CORK: "County Cork Ire or Cork City",
  CORN: "Cornwall England",
  CORO: "Corop",
  CORO: "Cororooke",
  CORR: "Corryong",
  COST: "Costerfield",
  COSTERFIEL: "Costerfield",
  COSTFIELD: "Costerfield",
  "COUNTY DER": "County Derry Ireland",
  COWA: "Cowana",
  COWAN: "Cowana",
  COWE: "Cowes",
  COWI: "Cowie's Creek",
  COWL: "Cowley's Creek",
  COWW: "Cowwarr",
  COXT: "Coxtown",
  COYS: "Coys Diggings",
  "COYS DGS": "Coys Diggings",
  "COYS DIGGI": "Coys Diggings",
  "CP OTWAY": "Cape Otway",
  "CP SCHANCK": "Cape Schanck",
  "CPBELLS C": "Campbells Creek (2)",
  CRAI: "Craigie",
  CRAI: "Craigieburn",
  CRAIGGIE: "Craigieburn",
  "CRAIGIE BU": "Craigieburn",
  CRAIGIEBRN: "Craigieburn",
  CRAN: "Cranbourne",
  CRAW: "Crawford River",
  CRES: "Cressy",
  CRES: "Creswick",
  CROO: "Crooked River",
  CROOKE: "Cororooke",
  CROS: "Crosbie",
  CROS: "Crossley",
  CROW: "Crowlands",
  CROX: "Croxton",
  CRSWK: "Creswick",
  CSPRGS: "Clifton Springs",
  CTON: "Carlton",
  CUDG: "Cudgee Creek",
  CUMB: "Cumberland England",
  CUND: "Cundare",
  CWELL: "Camberwell",
  CWICK: "Creswick",
  CWOOD: "Collingwood",
  "CWOOD FLT": "Collingwood Flat",
  DABY: "Dabyminga",
  DAIS: "Daisy Hill",
  "DAISY H": "Daisy Hill",
  DALH: "Dalhousie County",
  DAMP: "Damper Creek",
  DAND: "Dandenong",
  DARE: "Darebin",
  DARG: "Dargalong",
  DARG: "Dargo",
  DARI: "Darriwell",
  DARL: "Darlimurla",
  DARLINGFD: "Darlingford",
  DARLTON: "Darlington (2)",
  DARR: "Darraweit Guim",
  DARR: "Darrinal",
  DARR: "Darriwell",
  DARRI: "Darriwell",
  DART: "Dartmoor",
  DAYL: "Daylesford",
  DEAD: "Deadhorse Flat",
  DEAD: "Deadhorse Gully",
  "DEAD H GY": "Deadhorse Gully",
  "DEAN MARS": "Deans Marsh",
  "DEANS M": "Deans Marsh",
  "DEANS MSH": "Deans Marsh",
  DEDE: "Dederang",
  DEEP: "Deep Creek (6)",
  "DEEP CRK": "Deep Creek (6)",
  "DEEP LD": "Deep Lead",
  DELA: "Delatite",
  DENI: "Deniliquin",
  DENN: "Dennington",
  DEPT: "Deptford",
  DERB: "Derbyshire England",
  DERE: "Dereel",
  DERG: "Dergholm",
  DERR: "County Derry Ireland",
  DERR: "Derrimut",
  DEVE: "Devenish",
  DEVI: "Devils River",
  "DEVI RIV": "Devils River",
  DEVO: "Devon England",
  DFORD: "Daylesford",
  DGTON: "Darlington (2)",
  DIGB: "Digby",
  DIGG: "Diggorra",
  "DIGGERS R": "Digger's Rest",
  "DIGGERS RE": "Digger's Rest",
  "DIGGERS RS": "Digger's Rest",
  "DIGGERS RT": "Digger's Rest",
  DIMB: "Dimboola",
  DKELD: "Dunkeld",
  DLINGTON: "Darlington (2)",
  DLLY: "Dunolly",
  DMOND: "Diamond Creek",
  DNONG: "Dandenong",
  "DO NA": "Donald",
  "DO NC": "Doncaster",
  DOBI: "Dobie's Bridge",
  DOCK: "Docker's Plains",
  DOCT: "Doctor's Creek or Gully",
  DOGT: "Dogtrap Creek",
  DOLL: "Dolly's Creek",
  DOLLY: "Dolly's Creek",
  DOLLY: "Dunolly",
  DON: "Donald",
  DONA: "Donald",
  DONC: "Doncaster",
  DONK: "Donkey Hill",
  DONN: "Donnelly's Creek (2)",
  DONN: "Donnybrook",
  "DONNY CR": "Donnelly's Creek (2)",
  DONNYBK: "Donnybrook",
  DOOE: "Dooen",
  DOOK: "Dookie",
  DOWL: "Dowling Flat",
  DOWL: "Dowling Forest",
  DOWN: "County Down Ireland",
  DROM: "Dromana",
  DROM: "Dromana Ireland",
  DROU: "Drouin",
  DRUM: "Drummond",
  DRUN: "Drung-Drung",
  "DRY DIGGIN": "Dry Diggings",
  "DRY DIGGS": "Dry Diggings",
  DRYC: "Dry Creek (2)",
  DRYD: "Dry Diggings",
  DRYD: "Drysdale",
  DRYD: "Drysdale Creek",
  DTON: "Darlington (2)",
  DUBL: "Dublin Ireland",
  DUCH: "Duchembeg",
  DUCK: "Duck Ponds",
  "DUCK PDS": "Duck Ponds",
  "DUCK PNDS": "Duck Ponds",
  DUNB: "Dunbulbalane",
  DUNBUBALAN: "Dunbulbalane",
  "DUNBULBA-L": "Dunbulbalane",
  DUND: "Dundas",
  DUND: "Dundee Scotland",
  DUNE: "Duneed",
  DUNK: "Dunkeld",
  DUNKEL: "Dunkeld",
  DUNM: "Dunmore",
  DUNO: "Dunolly",
  DURDIDWAH: "Durdidwarrah",
  DURDIDWARR: "Durdidwarrah",
  DURH: "Durham Lead",
  DURH: "Durhamox",
  "E BELLA": "East Bellarine",
  "E DORADO": "Eldorado",
  "E HILL": "Eastern Hill",
  "E HILL": "Emerald Hill",
  "EAG'HAWK": "Eaglehawk",
  EAGL: "Eaglehawk",
  EAGLE: "Eaglehawk",
  "EAGLHK GY": "Eaglehawk",
  "EAST BTON": "East Brighton",
  "EAST CHARL": "East Charlton",
  ECHU: "Echuca",
  ECKL: "Ecklin Creek",
  ECLI: "Eclipse",
  EDDI: "Eddington",
  EDEN: "Edenhope",
  EDGE: "Edgecombe",
  EDHOPE: "Edenhope",
  EDON: "Essendon",
  EDWA: "Edwards River",
  EGAN: "Eganstown",
  EGER: "Egerton",
  "EH IL": "Emerald Hill",
  EHAWK: "Eaglehawk",
  EHAWK: "Eaglehawk",
  EHIL: "Emerald Hill",
  EHOPE: "Edenhope",
  ELAI: "Elaine",
  ELDO: "Eldorado",
  ELGA: "Elgar's Survey",
  "ELGARS SUR": "Elgar's Survey",
  "ELGARS SVY": "Elgar's Survey",
  ELLE: "Ellerslie",
  ELLI: "Elliminyt",
  ELMH: "Elmshurst",
  ELMO: "Elmore",
  ELPHIN: "Elphinstone",
  ELPHINST: "Elphinstone",
  ELST: "Elsternwick",
  ELSTWICK: "Elsternwick",
  ELTH: "Eltham",
  ELWICK: "Elsternwick",
  ELWO: "Elwood",
  ELYS: "Elysian Flat",
  "EM ER": "Emerald Hill",
  EMBE: "Emberton",
  "EMD HILL": "Emerald Hill",
  "EMER H": "Emerald Hill",
  "EMLD HILL": "Emerald Hill",
  ENFI: "Enfield",
  ENG: "England",
  ENOC: "Enoch's Point",
  EPPI: "Epping",
  EPSO: "Epsom",
  ESS: "Essendon",
  ESSDON: "Essendon",
  ESSE: "Essendon",
  ESTC: "Estcourt",
  EUME: "Eumemerring Creek",
  EUME: "Eumerella River",
  EUR: "Euroa",
  EUR: "Europa Gully",
  EURA: "Eurambeen",
  EURE: "Eureka Reef",
  EURO: "Euroa",
  EURO: "Eurobin",
  EURO: "Euroke",
  EURO: "Europa Gully",
  EVAN: "Evansford",
  EVEL: "Evelyn",
  EVER: "Eversley",
  EVER: "Everton",
  EWIK: "Elsternwick",
  F: "Fitzroy",
  FAIT: "Faithfull's Creek",
  FARA: "Faraday",
  FARN: "Farnham",
  "FARNHAM S": "Farnham's Special Survey",
  "FARNHAM SU": "Farnham's Special Survey",
  FBURGH: "Freeburgh",
  FCRAY: "Footscray",
  FCY: "Footscray",
  FENT: "Fenton's Creek",
  FERM: "County Fermanagh Ireland",
  FERMANAGH: "County Fermanagh Ireland",
  FERN: "Fernhurst",
  "FERN TG": "Fern Tree Gully",
  FIER: "Fiery Creek",
  "FIRST WHITE": "First White Hill",
  "FIRST WT H": "First White Hill",
  FITZ: "Fitzroy",
  "FITZ N": "North Fitzroy",
  "FIVE MILE": "Five Mile Creek (4)",
  "FLAGSF GL": "Flagstaff Gully",
  FLEM: "Flemington",
  FLET: "Fletcher's Creek",
  FLIN: "Flinders",
  FLOO: "Flooding Creek",
  FLTON: "Flemington",
  FLYN: "Flynn's Creek (2)",
  FOO: "Footscray",
  FOOT: "Footscray",
  FORB: "Forbes",
  FORE: "Forest Creek (2)",
  FORE: "Forest Creek Diggings",
  FORT: "Fort William Scotland",
  FORT: "Forty Foot",
  "FORT WILLI": "Fort William Scotland",
  "FORT WM": "Fort William Scotland",
  FOST: "Foster",
  FOUR: "Four Mile Creek (2) or Flat",
  "FOUR MLE F": "Four Mile Creek (2) or Flat",
  FRAM: "Framlingham",
  FRAMLINGHA: "Framlingham",
  FRAN: "France",
  FRAN: "Franklinford",
  FRAN: "Frankston",
  FREE: "Freeburgh",
  FREN: "French Island",
  FREN: "Frenchman's Creek (2)",
  FREN: "Frenchman's Gully",
  FREN: "Frenchman's Swamp",
  FRES: "Freshwater Creek",
  "FREY (sp)": "Fryers",
  "FREY (sp)": "Fryerstown",
  FROY: "Fitzroy",
  FRYE: "Fryers",
  FRYE: "Fryerstown",
  FSCRAY: "Footscray",
  FSTON: "Frankston",
  "FTH WHT HL": "Fourth or Fifth White Hill",
  FTON: "Flemington",
  FTON: "Frankston",
  "FTON AND KTN": "Flemington and Kensington",
  FYAN: "Fyansford",
  GABO: "Gabo Island",
  GAFF: "Gaffney's Creek (2)",
  GAL: "County Galway Ireland",
  GALW: "County Galway Ireland",
  GARD: "Gardiner",
  GARD: "Gardiner's Creek (2)",
  GARDNSCK: "Gardiner's Creek (2)",
  "GARDR CR": "Gardiner's Creek (2)",
  GARV: "Garvoc",
  GEE: "Geelong",
  GEEL: "Geelong",
  GELL: "Mount Gellibrand",
  GEMB: "Gembrook",
  GENO: "Genoa",
  GERHAP: "Geringhap",
  GERM: "Germantown",
  GFORD: "Guildford",
  GHER: "Geringhap",
  GIBR: "Gibraltar",
  GIPP: "Gippsland",
  GIPPSLD: "Gippsland",
  GISB: "Gisborne",
  GLAN: "Glangile",
  GLAS: "Glasgow Scotland",
  GLED: "Gledefield",
  GLEN: "Glenburn",
  GLEN: "Glendaruel",
  GLEN: "Glendonald",
  GLEN: "Glengower",
  GLEN: "Glenluce",
  GLEN: "Glenlyon",
  GLEN: "Glenmaggi",
  GLEN: "Glenorchy",
  GLEN: "Glenpatrick",
  GLEN: "Glenroy",
  "GLEN TSON": "Glenthompson",
  GLENTHOMS: "Glenthompson",
  GLONG: "Geelong",
  GNAR: "Gnarwarre",
  "GO RD": "Gordon",
  "GO RD": "Gordons Dig",
  GOBU: "Gobur",
  GOLD: "Goldborough",
  GOLD: "Goldie",
  "GOLDEN SQ": "Golden Square",
  GOOL: "Gooley's Creek",
  GOOR: "Gooramadda",
  GOOR: "Goorambat",
  GOOR: "Goornong",
  GOOR: "Gooroc",
  GORD: "Gordon",
  GORD: "Gordons Dig",
  GORO: "Goroke",
  GOSL: "Gosling's Creek",
  GOUL: "Goulburn River",
  "GOULBN RIV": "Goulburn River",
  GOWA: "Gowangarrie",
  GOWA: "Gowar",
  GOWAN: "Gowangarrie",
  GPLD: "Golden Point",
  GRAM: "Grampian Ranges",
  GRAN: "Grant",
  GRAN: "Grantville",
  GRAN: "Mount Granya",
  GRAN: "The Grange",
  GRAS: "Grassdale Creek",
  GRAS: "Grassy Flat",
  GRAY: "Graytown",
  GREA: "Great Western",
  "GREAT W": "Great Western",
  "GREAT WEST": "Great Western",
  GREE: "Greece",
  GREE: "Green Dale",
  GREE: "Green Gully",
  GREE: "Green Hill (5)",
  GREE: "Green Valley",
  GREE: "Greensborough",
  GREE: "Greenvale",
  GREE: "Grenville",
  "GREEN SWAM": "Green Swamp",
  GREENSBGH: "Greensborough",
  GRET: "Greta",
  GRIF: "Griffith's Point",
  GRIT: "Gritjurk",
  GROW: "Growlers Creek",
  GTHOMPSON: "Glenthompson",
  GUIL: "Guildford",
  GUMT: "Gum Tree Flat",
  GUNB: "Gunbower",
  GVALE: "Glenvale",
  "HA WK": "Hawksedale",
  HADD: "Haddon",
  HAM: "Hampton",
  HAMB: "Hamburg Germany",
  HAMI: "Hamilton",
  HAMP: "Hampden",
  HAMP: "Hampton",
  HAPP: "Happy Valley",
  "HAPPY VY": "Happy Valley",
  HARC: "Harcourt",
  HARD: "Hard Hills",
  HARD: "Hardie's Hill",
  HARK: "Harkaway (2)",
  HARR: "Harrietville",
  HARR: "Harrow",
  HART: "Hartley",
  HART: "Hartwell",
  HAST: "Hastings",
  HAUN: "Haunted Hill or Gully",
  HAVE: "Havelock",
  HAWK: "Hawksedale",
  HAWS: "Hawstead",
  HAWT: "Hawthorn",
  HAWTH: "Hawthorn",
  HAYA: "Hayanmi",
  HAYF: "Hayfield",
  HAZE: "Hazlewood",
  HAZL: "Hazlewood",
  HBERG: "Heidelberg",
  HCOTE: "Heathcote",
  HCOURT: "Harcourt",
  HDALE: "Hawksedale",
  "HE SPRINGS": "Hepburn Springs",
  HEAL: "Healsville",
  HEAT: "Heathcote",
  HEID: "Heidelberg",
  HEPB: "Hepburn",
  HERN: "Hern Hill",
  HESK: "Hesket",
  HEXH: "Hexham",
  HEYF: "Heyfield",
  HEYT: "Heytesbury",
  HEYW: "Heywood",
  HILL: "Hillarney",
  HILLSBGH: "Hillsborough",
  HILLSBORH: "Hillsborough",
  HISC: "Hiscock's Reef or Gully",
  HLEY: "Huntly",
  HLTON: "Hamilton",
  "HO TH": "Hotham",
  HOBA: "Hobart Tasmania",
  HOCH: "Hochkirch",
  HODD: "Hoddle's Range or Creek",
  HOLD: "Holden",
  HOLL: "Holland Europe",
  HOMB: "Homebush",
  HOME: "Homebush",
  HONE: "Honeysuckle",
  HOPK: "Hopkins River or Hill",
  HOREH: "Hore's Hill",
  HORS: "Horsham",
  HORSH: "Horsham",
  HOTH: "Hotham",
  "HOTH E": "Hotham East",
  HOTS: "Hotspur",
  HOVE: "Hovell's Creek",
  HOWQ: "Howqua Bridge or River",
  HTHORN: "Hawthorn",
  HTON: "Hamilton",
  HTON: "Highton",
  HUGH: "Hughes Creek",
  HUNT: "Huntly",
  HURD: "Hurdle Flat",
  HVILLE: "Harrietville",
  HYWOOD: "Heywood",
  IGUA: "Iguana Creek",
  IHOE: "Ivanhoe",
  ILLA: "Illabarook",
  "IN GL": "Inglewood",
  "IN VE": "Inverleigh",
  INDE: "Indented Head",
  "INDE HD": "Indented Head",
  INDI: "Indigo",
  INGL: "Inglewood",
  INKE: "Inkerman",
  INVE: "Inverleigh",
  IRE: "Ireland",
  IRED: "Ireland",
  IREL: "Ireland",
  IRIS: "Irish Town (3)",
  "IRISH TN": "Irish Town (3)",
  IRISHT: "Irish Town (3)",
  IRIST: "Irish Town (3)",
  IRLD: "Ireland",
  IRON: "Ironbark Gully",
  IRRE: "Irrewarra",
  "ISTONE HILL": "Ironstone Hill",
  ITAL: "Italy Europe",
  ITAL: "Italian Gully",
  IVAN: "Ivanhoe",
  IWOOD: "Inglewood",
  JACA: "Jacana",
  JACK: "Jackass Flat",
  JACK: "Jackson's Gully",
  JAMI: "Jamieson",
  "JAMIESON S": "Jamieson's survey",
  JANE: "Janefield",
  JANJ: "Jan Juc (2)",
  JEFF: "Mount Jeffcott",
  JERI: "Jericho (2)",
  JERI: "Jericho Creek",
  JERU: "Jerusalem Creek",
  JIM: "Jim Crow Creek",
  JIMC: "Jim Crow Creek",
  JOBS: "Jobs Gully",
  "JOBS G": "Jobs Gully",
  JOLI: "Jolimont",
  JONE: "Jones Creek (2)",
  JORD: "Jordan",
  JOYC: "Joyce's Creek",
  JUMB: "Jumbunna",
  JUNC: "Junction (2)",
  JUNG: "Jung Jung",
  "KA NG": "Kangaroo Ground",
  "KA NG": "Kangaroo",
  KAAR: "Kaarimba",
  KALK: "Kalkallo",
  KALY: "Kalymna",
  KAMA: "Kamarooka",
  KANG: "Kangaroo Ground",
  KANG: "Kangaroo",
  KANG: "Kangaroo Range (2)",
  KANG: "Kangaroo Flat",
  "KANGO FLA": "Kangaroo Flat",
  KANI: "Kaniva",
  KARA: "Karabeal",
  KARD: "Kardinia",
  KARK: "Karkarooc County",
  KARN: "Karngun",
  KARN: "Karnak",
  KARN: "Lake Karnack",
  KARR: "Karramomus",
  KATA: "Katamatite",
  KATA: "Katandra",
  KBRAM: "Kyabram",
  KBURRA: "Korumburra",
  KEI: "Keilor",
  KEIL: "Keilor",
  "KEIL PLN": "Keilor Plains",
  KELL: "Kellalac",
  KENGTON: "Kensington (2)",
  KENN: "Kennedy's Creek",
  KENS: "Kensington (2)",
  KENTON: "Kensington (2)",
  KER: "County Kerry Ireland",
  KERA: "Kerang",
  KERI: "Kerington",
  KERR: "County Kerry Ireland",
  KERRY: "County Kerry Ireland",
  "KEW L ASY": "Kew Lunatic Asylum",
  KEYA: "Keyanga Marsh",
  KFLAT: "Kangaroo Flat",
  KHUL: "Khull's Range",
  KIAL: "Kialla",
  KIAT: "Kiata",
  KIEW: "Kiewa",
  KIL: "Kilmore",
  KILD: "County Kildare Ireland",
  KILD: "Kildare",
  KILK: "County Kilkenny Ireland",
  KILL: "Killarney",
  KILM: "Kilmore",
  KING: "Kingower",
  KING: "Kings County Ireland (Co Offaly)",
  KING: "Kingston",
  KINGOW: "Kingower",
  KINL: "Kinlochewe",
  KINL: "Kinloch",
  KIOR: "Kiora",
  KIRK: "Kirkstall",
  KMORE: "Kilmore",
  KOLO: "Kolomgolac",
  KOLO: "Kolora",
  KONO: "Konongwootong",
  KOON: "Koondrook",
  KORN: "Korwienguboora",
  KORO: "Koroit",
  KORO: "Korong",
  KORO: "Mount Korong",
  KORWEINGUB: "Korwienguboora",
  KRAM: "Krambruk",
  "KROO FL": "Kangaroo Flat",
  KSTALL: "Kirkstall",
  KTON: "Kyneton",
  "KY AB": "Kyabram",
  KYN: "Kyneton",
  KYNE: "Kyneton",
  KYTON: "Kyneton",
  "L BURNER": "Limeburner's Bay",
  LAAN: "Laanecoorie",
  LAKE: "Lake Bolac",
  LAKE: "Lake Marmal",
  "LAKE KILLE": "Lake Killear",
  "LAKE TERAN": "Lake Terang",
  LAL: "Lal-Lal",
  LALL: "Lal-Lal",
  LAMB: "Lambeth UK",
  LAMP: "Lamplough",
  LANC: "Lancefield",
  LAND: "Landsborough",
  LANDBGH: "Landsborough",
  LANDSBOR: "Landsborough",
  LANG: "Langullac",
  LANG: "Langley",
  "LANGI KAL": "Langi Kal Kal",
  "LANGI LOGA": "Langi Logan",
  LANI: "Laanecoorie",
  LARD: "Lardner",
  LARP: "Larpent",
  LATR: "Mount Latrobe",
  LATR: "Latrobe's Range",
  LATR: "Latrobe River",
  LAUN: "Launceston Tasmania",
  LAUR: "Lauriston",
  LAWL: "Lawloit",
  LAYA: "Layard",
  LBORO: "Landsborough",
  LBOROUGH: "Landsborough",
  LDSBOROUGH: "Landsborough",
  LEAR: "Learmonth",
  LEDC: "Ledcourt",
  LEIC: "Leicester England",
  LEIC: "Leichardt",
  LEIG: "Leigh Creek",
  LEIG: "Leigh Road",
  LEIG: "Leigh River",
  LEIG: "The Leigh",
  LEIGH: "The Leigh",
  LEIT: "County Leitrim Ireland",
  LEIT: "Leith Scotland",
  LEMO: "Lemon Springs",
  LEON: "Leongatha",
  LETH: "Lethbridge",
  LETHB: "Lethbridge",
  LEUR: "Leura",
  LEXT: "Lexton",
  LEXTO: "Lexton",
  LFIELD: "Lancefield",
  LGULLY: "Long Gully (2)",
  LILI: "Lillimur",
  LILI: "Lillicur",
  LILL: "Lillimur",
  LILL: "Lillicur",
  LILY: "Lilydale",
  LIM: "County Limerick or Limerick City",
  LIME: "County Limerick or Limerick City",
  "LIME BURNER": "Limeburner's Bay",
  LIND: "Lindenow Flat",
  LINL: "Lake Linlithgow",
  LINL: "Linlithgowshire Scotland",
  LINT: "Linton's",
  LINTON: "Linton's",
  LISM: "Lismore",
  LITT: "Little River (4)",
  "LITTLE BEN": "Little Bendigo",
  "LITTLE ELT": "Little Eltham",
  "LITTLE FOR": "Little Forest",
  "LITTLE HD H": "Little Hard Hills",
  "LITTLE R": "Little River (4)",
  LIV: "Livingston",
  LIV: "Liverpool England",
  LIVE: "Liverpool England",
  "LK WELLING": "Lake Wellington",
  LLAN: "Llanelly",
  LOCK: "Lockwood",
  LOCK: "Lockington",
  LODD: "Loddon",
  LONG: "Long Gully (2)",
  LONG: "Longwarry",
  LONG: "Long Point",
  LONG: "Longwood",
  "LONG GLY": "Long Gully (2)",
  LONGERENON: "Longerenong",
  LONGFOR: "County Longford Ireland",
  LONGFOR: "Longford",
  LORN: "Lorne",
  LOUT: "Loutitt Bay",
  LOWA: "Lowan County",
  LOWE: "Lower Cape",
  LOWR: "Lowry",
  LOYO: "Loyola",
  "LT BENGO": "Little Bendigo",
  "LT BRIGHTN": "Little Brighton",
  "LT BRTON": "Little Brighton",
  "LT SCOT": "Little Scotland",
  "LT SCOTL": "Little Scotland",
  LUCK: "Lucknow",
  "LUCKY WM": "Lucky Woman's",
  "LUCKY WMN": "Lucky Woman's",
  "LUCKY WOMA": "Lucky Woman's",
  "LUCKY WOMN": "Lucky Woman's",
  LWOOD: "Lockwood",
  LYND: "Lyndhurst",
  LYST: "Lysterfield",
  "M DORAN": "Mount Doran",
  "M PONDS": "Moonee Ponds",
  "M RAGLAN": "Mount Raglan",
  "M ROUSE": "Mount Rouse",
  "MA CA": "Macao China",
  "MA CA": "Macarthur",
  "MA ID": "Maidstone",
  MACA: "Macao China",
  MACA: "Macarthur",
  MACE: "Macedon",
  MACK: "Macklin Creek",
  MADD: "Maddingley",
  MAFF: "Maffra",
  MAGP: "Magpie Diggings",
  MAGP: "Magpie (2)",
  MAGP: "Magpie Gully",
  MAID: "Maidstone",
  MAIL: "Mailors Flat",
  MAIN: "Maindample",
  MAJO: "Majorca",
  MALA: "Malakoff",
  "MAL'BURY": "Malmsbury",
  MALD: "Maldon",
  MALLOC: "Mordialloc",
  MALM: "Malmsbury",
  MALMS: "Malmsbury",
  MALV: "Malvern",
  MAND: "Mandurang",
  MANG: "Mangalore",
  MANI: "Manifold Creek",
  MANI: "Manilla Phillipines",
  MANS: "Mansfield",
  MARI: "Maribyrnong River",
  MARO: "Marong",
  MARS: "Marshalltown",
  MARSHLTWN: "Marshalltown",
  MARY: "Maryborough",
  MARYBGH: "Maryborough",
  MARYBORGH: "Maryborough",
  MARYBORH: "Maryborough",
  MATL: "Matlock",
  MAUD: "Maude",
  MBEENA: "Murrumbeena",
  MBOOL: "Moorabool",
  MBORO: "Maryborough",
  MBRO: "Maryborough",
  MBURY: "Malmsbury",
  MCCU: "McCullums Creek",
  McIN: "McIntyre Diggings",
  MCIN: "McIntyre Diggings",
  "MCINTYRE D": "McIntyre Diggings",
  MCINTYRES: "McIntyre Diggings",
  MCIV: "McIvor Diggings",
  MDON: "Maldon",
  MDUKE: "Murdaduke",
  MDURA: "Mildura",
  MEL: "Melbourne",
  MELB: "Melbourne",
  "MELB E": "East Melbourne",
  "MELB W": "West Melbourne",
  MELT: "Melton",
  MEPU: "Mepunga",
  MERC: "Mercers Hill",
  MERC: "Mercer's Vale",
  MERE: "Meredith",
  MERI: "Merriang",
  MERI: "Merino",
  MERR: "Merriang",
  MERR: "Merri River",
  MERR: "Merri Creek",
  MERRI: "Merri River",
  MERRI: "Merriang",
  MERRI: "Merri Creek",
  "MERRI CRK": "Merri Creek",
  MERRIMAN: "Merriman's Creek",
  MERT: "Merton",
  METC: "Metcalfe",
  MFIELD: "Mansfield",
  MFORD: "Muckleford",
  MGETTA: "Monegatta (Monegeetta)",
  MGRAVE: "Mulgrave",
  "MI NY": "Minyip",
  MIAM: "Mia Mia",
  MICKHAM: "Mickleham",
  MICKLAM: "Mickleham",
  MIDD: "Middleton's Creek",
  MIDD: "Middle Creek (6)",
  MIDD: "Middlesex England",
  MILK: "Milkmaids Flat",
  MILK: "Milkman's Flat",
  MILL: "Millbrook",
  MINE: "Miners Rest",
  "MINERS R": "Miners Rest",
  MINY: "Minyip",
  MIRB: "Mirboo",
  "MIRB N": "Mirboo North",
  MIRR: "Mirradong",
  MITC: "Mitcham",
  MITI: "Mitiamo",
  MITT: "Mitta Mitta",
  MKFORD: "Muckleford",
  MLAKE: "Mortlake",
  MODE: "Modewarre",
  MOLI: "Moliagul",
  "MON MOUTHSH": "Monmouthshire England",
  MONAGHAN: "County Monaghan Ireland",
  MONE: "Monegatta (Monegeetta)",
  MONEGEETT: "Monegatta (Monegeetta)",
  MONK: "Monkey Gully",
  MONM: "Monmouth England",
  MONM: "Monmouthshire England",
  "MONT PK": "Mont Park",
  MOOL: "Moolap",
  MOON: "Moonambel",
  MOON: "Moonee Ponds",
  MOON: "Moonlight Flat",
  "MOON FL": "Moonlight Flat",
  MOONA: "Moonambel",
  MOONBEL: "Moonambel",
  "MOONEE PDS": "Moonee Ponds",
  MOOR: "Moorabbin",
  MOOR: "Moorooduc",
  MOOR: "Mooroopna",
  MORA: "Moranding",
  MORA: "Morangourk",
  MORA: "Morang",
  MORD: "Mordialloc",
  MORDING: "Moranding",
  MORDLLOC: "Mordialloc",
  MORDOC: "Mordialloc",
  MORNTON: "Mornington",
  MORR: "Morrison's",
  MORS: "Morse's Creek",
  MORT: "Mortlake",
  MOSQ: "Mosquito Flat",
  MOSQ: "Mosquito Flat",
  MOSQ: "Mosquito",
  MOUN: "Mount Misery",
  MOUN: "Mountain Creek (2)",
  MOUN: "Mountain Hut",
  "MOUNT DORA": "Mount Doran",
  "MOUNT ROUS": "Mount Rouse",
  "MOUNT WILL": "Mount William",
  "MOUNTAIN C": "Mountain Creek (2)",
  "MOUNTAIN H": "Mountain Hut",
  MOUT: "Moutajup",
  MOYH: "Moyhu",
  MOYS: "Moyston",
  MPNA: "Mooroopna",
  MSBURY: "Malmsbury",
  MSTONE: "Maidstone",
  "MT AL": "Mount Alexander (2)",
  "MT ALEXR": "Mount Alexander (2)",
  "MT AR": "Mount Ararat (2)",
  "MT ATKINSO": "Mount Atkinson",
  "MT B": "Mount Blackwood",
  "MT BA": "Mount Battery",
  "MT BALLT": "Mount Ballarat",
  "MT BEAUFOR": "Mount Beauford",
  "MT BECKWIT": "Mount Beckworth",
  "MT BECKWTN": "Mount Beckworth",
  "MT BL": "Black Mount",
  "MT BLACKD": "Mount Blackwood",
  "MT BLACKW": "Mount Blackwood",
  "MT BLOWHD": "Mount Blowhard",
  "MT BLWOOD": "Mount Blackwood",
  "MT BO": "Mount Bolton",
  "MT BU": "Mount Buninyong",
  "MT CL": "Mount Clear",
  "MT CL": "Mount Clare",
  "MT CO": "Mount Cole",
  "MT CO": "Mount Cotterell",
  "MT COTT": "Mount Cotterell",
  "MT COTTEL": "Mount Cotterell",
  "MT COTTER": "Mount Cotterell",
  "MT COTTERE": "Mount Cotterell",
  "MT DO": "Mount Doran",
  "MT ECKSLY": "Mount Eckersley",
  "MT EDGERTO": "Mount Egerton",
  "MT EG": "Mount Egerton",
  "MT EGERT": "Mount Egerton",
  "MT EGTON": "Mount Egerton",
  "MT EL": "Mount Elephant",
  "MT ELPHT": "Mount Elephant",
  "MT EM": "Mount Emu (2)",
  "MT EM": "Mount Emu Creek",
  "MT EMU": "Mount Emu Creek",
  "MT EV": "Mount Evelyn",
  "MT FR": "Mount Franklin Shire",
  "MT FY": "Mount Fyans",
  "MT GA": "Mount Gambier",
  "MT GELL": "Mount Gellibrand",
  "MT GELLD": "Mount Gellibrand",
  "MT GELLIBR": "Mount Gellibrand",
  "MT GI": "Mount Gisborne",
  "MT GR": "Mount Greenock",
  "MT GREENK": "Mount Greenock",
  "MT GREENOC": "Mount Greenock",
  "MT JE": "Mount Jeffcott",
  "MT JEFF": "Mount Jeffcott",
  "MT KO": "Mount Korong",
  "MT KORO": "Mount Korong",
  "MT KORON": "Mount Korong",
  "MT LO": "Mount Look-Out",
  "MT MA": "Mount Macedon",
  "MT MA": "Mt Macedon",
  "MT ME": "Mount Mercer",
  "MT MI": "Mount Misery",
  "MT MO": "Mount Moriac",
  "MT MO": "Mt Moliagul",
  "MT MORIA": "Mount Moriac",
  "MT NA": "Mount Napier",
  "MT PL": "Mount Pleasant (6)",
  "MT PLEASAN": "Mount Pleasant (6)",
  "MT PLEAST": "Mount Pleasant (6)",
  "MT PR": "Mount Prospect (3)",
  "MT PROS": "Mount Prospect (3)",
  "MT PROSP": "Mount Prospect (3)",
  "MT PROSPEC": "Mount Prospect (3)",
  "MT RO": "Mount Rouse",
  "MT SH": "Mount Shadwell",
  "MT ST": "Mount Sturgeon",
  "MT STURGEO": "Mount Sturgeon",
  "MT STURGN": "Mount Sturgeon",
  "MT WA": "Mount Washington",
  "MT WILLM": "Mount William",
  "MTAIN CK": "Mountain Creek (2)",
  MTAL: "Mount Alexander (2)",
  MTAR: "Mount Ararat (2)",
  MTBL: "Mount Blowhard",
  MTBLACKWD: "Mount Blackwood",
  MTBLKWOOD: "Mount Blackwood",
  MTBO: "Mount Bolton",
  MTDU: "Mount Duneed",
  MTEG: "Mount Egerton",
  MTGR: "Mount Greenock",
  MTMA: "Mount Macedon",
  MTMO: "Mount Moriac",
  MTOA: "Murtoa",
  "M'TON": "Mornington",
  MTPR: "Mount Prospect (3)",
  MTWA: "Mount Warrenheip",
  MUCK: "Muckleford",
  MUCKLEFRD: "Muckleford",
  MUDD: "Muddy Creek (3)",
  "MUDD CRK": "Muddy Creek (3)",
  MUDG: "Mudgegonga",
  MULG: "Mulgrave",
  MUND: "Mundoona",
  MUNSTER: "Barony of Munster Ireland",
  MUNSTER: "Munster Ireland",
  MUNT: "Muntham",
  MURC: "Murchison",
  MURCHSN: "Murchison",
  MURD: "Lake Murdeduke",
  MURG: "Murgheboluc",
  MURGHBOLUC: "Murgheboluc",
  MURGHEBOLA: "Murgheboluc",
  MURM: "Murmungee",
  MURN: "Murndal",
  MURR: "Murray District",
  MURR: "Murray River",
  MURR: "Murrumbeena",
  "MURRAY DIS": "Murray District",
  MURT: "Murtoa",
  MUSK: "Musk Vale",
  MVERN: "Malvern",
  MVILLE: "Marysville",
  MWEL: "Morwell",
  MYER: "Myer's Flat",
  MYFORD: "Myrtleford",
  MYRN: "Myrniong",
  MYRT: "Myrtle Creek (2)",
  MYRT: "Myrtleford",
  MYRTLEF: "Myrtleford",
  MYSI: "Mysia",
  "N BRIDGE": "Newbridge",
  "N EDON": "North Essendon",
  "N,COTE": "Northcote",
  "NA PO": "Napoleon's",
  NAGA: "Nagambie",
  NAPO: "Napoleon's",
  "NAR NAR GO": "Nar Nar Goon",
  NARR: "Narracan",
  NARR: "Narraport",
  NARRE: "Narrawong",
  NARRE: "Narree Warren",
  "NARRE W": "Narree Warren",
  "NARRE WN": "Narree Warren",
  NATH: "Nathalia",
  NATI: "Natimuk Creek",
  NATI: "Natimuk Lake",
  NATT: "Natte Yallock",
  "NATTE Y": "Natte Yallock",
  "NATTE YAL": "Natte Yallock",
  "NATTE YALLO": "Natte Yallock",
  NAVA: "Navarre",
  NEER: "Neerim",
  NEILBORO: "Neilborough",
  NEPE: "Point Napean",
  NERR: "Nerring",
  NEW: "Newlyn",
  NEW: "Newlands",
  NEW: "Newtown",
  "NEW GBORN": "New Gisborne",
  "NEW GISBN": "New Gisborne",
  "NEW GISBOR": "New Gisborne",
  "NEW SOUTH": "New South Wales",
  "NEW YERS": "New Year Flat",
  "NEW YR FLT": "New Year Flat",
  NEWB: "Newbridge",
  NEWB: "Newbury",
  NEWC: "New Chum Creek",
  NEWC: "Newcastle NSW",
  NEWC: "Newcastle England",
  NEWF: "Newfoundland Canada",
  NEWG: "New Gisborne",
  NEWH: "Newham",
  NEWI: "Newington",
  NEWL: "Newlyn",
  NEWL: "Newlands",
  NEWLAN: "Newlands",
  NEWM: "Newmarket",
  NEWP: "Newport",
  NEWP: "Newport England",
  NEWP: "Newport Wales",
  NEWR: "Newry",
  NEWS: "Newstead",
  NEWT: "Newtown",
  NEWY: "New Year Flat",
  NEWY: "New York",
  NEWZ: "New Zealand",
  NHIL: "Nhill",
  NILL: "Nillumbik",
  NINE: "Nine Creeks",
  "NINE ML CK": "Nine-Mile Creek",
  NINEMILECR: "Nine-Mile Creek",
  NINY: "Ninyeunook",
  NIRR: "Nirranda",
  NKAH: "Numurkah",
  NOOR: "Noorat",
  NOR: "Northcote",
  NORA: "Noradjuha",
  NORM: "Normanby County",
  NORT: "Northamptonshire England",
  NORT: "Northumberland England",
  NORT: "Northcote",
  NORW: "Norway Europe",
  NORW: "Norwood (2)",
  NOTT: "Nottinghamshire England",
  NOTTS: "Nottinghamshire England",
  NSTEAD: "Newstead",
  "NTH LFIEL": "Lancefield",
  NTOWN: "Newtown",
  NUGG: "Nuggetty Creek/Flat/Gully",
  NUMU: "Numurkah",
  NUN: "Nunawading",
  NUNA: "Nunawading",
  NUNT: "Nuntin Creek",
  NWADING: "Nunawading",
  OAK: "Oakleigh",
  OAKL: "Oakleigh",
  OGRVE: "Ocean Grove",
  "OLD INGWD": "Old Inglewood",
  "OLD INGWO": "Old Inglewood",
  "OLD IWOOD": "Old Inglewood",
  OLEIGH: "Oakleigh",
  ONDI: "Ondit",
  "ONE ML CRK": "One Mile Creek",
  ONEM: "One Mile Creek",
  OPOS: "Opossum Gully (2)",
  ORFO: "Orford",
  ORK: "Orkney Isles Scotland",
  ORKN: "Orkney Isles Scotland",
  ORMO: "Ormond",
  OSBO: "Osborne's Flat",
  OSBO: "Osborne",
  OURA: "Ouranna",
  OVEN: "Ovens River",
  OXLE: "Oxley",
  "P HILL": "Pyramid Hill",
  "P MELB": "Port Melbourne",
  PACK: "Pakenham",
  PADD: "Paddy's Gully",
  PAKE: "Pakenham",
  PALL: "Pall Mall",
  PALM: "Palmerston",
  PANM: "Panmure",
  PANNOOMILL: "Panoo Milloo",
  PARA: "Paraparap",
  PARK: "Parkville",
  PARL: "Portarlington",
  PARRAP: "Paraparap",
  PARW: "Parwan Creek",
  PASC: "Pascoe Vale",
  "PASCOE VAL": "Pascoe Vale",
  PAYN: "Paynesville",
  PEEC: "Peechelba",
  PEGL: "Peg Leg Gully",
  PENN: "Pennyweight Flat",
  PENNYWGHT: "Pennyweight Flat",
  "PENNYWT F": "Pennyweight Flat",
  PENS: "Penshurst",
  PENT: "Pentland Hills",
  PENT: "Pentridge",
  "PENTLAND H": "Pentland Hills",
  PENTLANDSH: "Pentland Hills",
  "PENTLD HL": "Pentland Hills",
  PERC: "Percydale",
  PERT: "Perth Western Australia",
  PERT: "Perth Scotland",
  "PETER DIGG": "Peter's Diggings",
  PETT: "Peter's Diggings",
  PETT: "Pettavel",
  PHEA: "Pheasant Creek",
  PHIL: "Phillip Island",
  PHIL: "Phillipstown",
  PHILLIPIS: "Phillip Island",
  PHURST: "Penshurst",
  "PI TF": "Pitfield",
  PICN: "Pic-Nic Point",
  PICO: "Picola",
  PIERREPOIN: "Mount Pierrepoint",
  PIGG: "Piggoreet",
  PIMP: "Pimpinio",
  PINE: "Mt Pine",
  PINE: "Pine Lodge",
  PINE: "Pine Grove",
  PIPE: "Piper's Creek (2)",
  PIRR: "Pirron Yalloak",
  "PIRRON YAL": "Pirron Yalloak",
  PISLAND: "Phillip Island",
  PITF: "Pitfield",
  "PL CK": "Pleasant Creek (2)",
  "PL CR": "Pleasant Creek (2)",
  PLAND: "Portland",
  PLEA: "Pleasant Creek (2)",
  PLEAS: "Pleasant Creek (2)",
  PLEASTCR: "Pleasant Creek (2)",
  PLEN: "Plenty",
  POLK: "Polkemet Lakes",
  POLW: "Polwarth County",
  POMB: "Pomborneit",
  POMP: "Pompapiel",
  POOW: "Poowong",
  POR: "Porcupine Flat",
  PORC: "Porcupine Flat",
  PORE: "Porepunkah",
  PORT: "Port Melbourne",
  PORT: "Portland",
  "PORT ALBER": "Point Albert",
  "PORT ARLING": "Portarlington",
  "PORT CAMPB": "Port Campbell",
  PORTD: "Portland",
  PORTO: "Portland",
  "PR ALF HOSP": "Prince Alfred Hospital",
  PRAH: "Prahran",
  PRES: "Preston",
  PRN: "Prahran",
  PROV: "Providence Ponds",
  "PROVDCE P": "Providence Ponds",
  "PT ALBT": "Point Albert",
  "PT CAMPBEL": "Port Campbell",
  "PT NAPEAN": "Point Napean",
  PTAL: "Point Albert",
  PTON: "Preston",
  PURN: "Purnim",
  PURR: "Lake Purrumbete",
  PURRUMBET: "Lake Purrumbete",
  PURRUMNEE: "Lake Purrumbete",
  PVILLE: "Parkville",
  "PY HILL": "Pyramid Hill",
  PYAL: "Pyalong",
  PYKE: "Mount Pyke,Creek",
  PYRA: "Pyramid Hill",
  PYRE: "Pyrenees Range",
  QCLIFFE: "Queenscliff",
  QLAND: "Queensland",
  QUAM: "Quambatook",
  QUAR: "Quarry Hill",
  QUEE: "Queens County Ireland",
  QUEE: "Queenstown (2)",
  QUEE: "Queenscliff",
  "QUEENS CLF": "Queenscliff",
  QUEENSCF: "Queenscliff",
  QUEENSFERR: "Queensferry",
  RAGL: "Raglan",
  RAMS: "Ramsgate",
  RASP: "Raspberry Creek",
  RATH: "Rathscar",
  RAVE: "Ravenswood",
  RAYW: "Raywood",
  RD: "Richmond",
  RDALE: "Rosedale",
  REDA: "Redan Hill",
  REDB: "Redbank",
  REDC: "Redcastle",
  REDE: "Redesdale",
  REDJ: "Red Jacket",
  REDR: "Redruth",
  REED: "Reedy Creek (5)",
  "REEVES SUR": "Reeve's Survey",
  REID: "Reid's Creek (2)",
  RESE: "Reservoir",
  RGLEN: "Rutherglen",
  RHEO: "Rheola",
  RHILL: "Red Hill (4)",
  RICH: "Richmond",
  RICHD: "Richmond",
  "RICHMOND F": "Richmond Flat",
  RIDD: "Riddell's Creek",
  RIFL: "Rifle Downs",
  RING: "Ringwood",
  RIPO: "Ripon County",
  RMOND: "Richmond",
  ROCH: "Rochester",
  ROCHTER: "Rochester",
  ROCK: "Rocky Bend",
  ROCK: "Rocky Lead (2)",
  "ROCKY L": "Rocky Lead (2)",
  RODN: "Rodney County",
  ROFORD: "Rochford",
  ROKE: "Rokewood",
  ROMS: "Romsey",
  ROSE: "Rosebrook (2)",
  ROSE: "Rosedale",
  ROSEBK: "Rosebrook (2)",
  ROSS: "Ross Scotland",
  ROSS: "Ross's Creek",
  ROSSHIRE: "Ross Shire Scotland",
  ROWA: "Lake Rowan",
  ROWS: "Rowsley",
  RUNN: "Running Creek (3)",
  RUNN: "Runnymede",
  RUPA: "Rupanyup",
  RUSS: "Russia",
  RUSS: "Russell's Creek",
  RUTH: "Rutherglen",
  RUTL: "Rutlandshire Eng",
  RUTL: "Rutland Eng",
  RWOOD: "Raywood",
  RWOOD: "Ringwood",
  RWOOD: "Rokewood",
  RWORTH: "Rushworth",
  "S Y": "South Yarra",
  "S YARR": "South Yarra",
  "S YARRA": "South Yarra",
  SAGO: "Sago Hill",
  SAIL: "Sailor's Gully",
  SAIL: "Sailor's Creek",
  SALI: "Salisbury West",
  SALT: "Salt Water River",
  "SALT CR": "Salt Creek (5)",
  "SALT WR RI": "Salt Water River",
  "SALT WTR C": "Salt Water Creek",
  "SALT WTR R": "Salt Water River",
  SAND: "Sandford,",
  SAND: "Sandon",
  SAND: "Sandridge",
  SANDY: "Sandy Creek (5)",
  "SANDY C": "Sandy Creek (5)",
  "SANDY CREE": "Sandy Creek (5)",
  "SANDY CRK": "Sandy Creek (5)",
  SARS: "Sarsfield",
  SAUS: "South Australia",
  SBURY: "Sunbury",
  SCAR: "Scarsdale",
  SCDALE: "Scarsdale",
  "SCH POINT": "Schnapper Point (2)",
  SCHN: "Schnapper Point (2)",
  "SCHNER PT": "Schnapper Point (2)",
  SCOR: "Scoresby",
  SCOT: "Scotchman's Lead",
  SCOT: "Scotland",
  SCOTCHMLD: "Scotchman's Lead",
  SCOTD: "Scotland",
  "SCOTMNS L": "Scotchman's Lead",
  SDALE: "Scarsdale",
  SDALE: "Smythesdale",
  SDALLAH: "Springdallah",
  SEA: "At sea",
  SEA: "Sealake",
  SEAC: "Seacombe",
  SEAF: "Seaford",
  SEAR: "Searsdale",
  SEAT: "Seaton",
  SEB: "Sebastopol (2)",
  SEBA: "Sebastopol (2)",
  SECO: "Second White Hill",
  "SECOND WHI": "Second White Hill",
  SEPA: "Sebastopol (2)",
  SERP: "Serpentine",
  SEVE: "Seven Creeks",
  "SEVEN W HI": "Seventh White Hill",
  SEXT: "Sexton",
  SEYM: "Seymour",
  SHAD: "Mount Shadwell",
  SHAM: "Sandringham",
  SHAN: "Shanghai China",
  SHEE: "Sheep Hill",
  SHEE: "Sheepshead Gully",
  SHEE: "Sheepwash Creek",
  "SHEEP H": "Sheep Hill",
  "SHEEP WAS": "Sheepwash Creek",
  "SHEEPHD GY": "Sheepshead Gully",
  "SHEEPSH G": "Sheepshead Gully",
  SHEF: "Sheffield England",
  SHEL: "Shelbourne",
  SHEL: "Shelford",
  SHELBNE: "Shelbourne",
  SHEO: "She-Oak Plains",
  SHEP: "Shepherd's Flat",
  SHEP: "Shepparton",
  "SHEPH FLAT": "Shepherd's Flat",
  "SHEPHERS F": "Shepherd's Flat",
  "SHEPHS FL": "Shepherd's Flat",
  SHEPP: "Shepparton",
  SHEPPTON: "Shepparton",
  SHEPTON: "Shepparton",
  SHET: "Shetland Islands England",
  SHIR: "Shirley",
  SHTON: "Shepparton",
  SHURST: "Sandhurst",
  SIXM: "Six-Mile Creek",
  "SIXTH WHITE": "Sixth White Hill",
  SKEL: "Skeleton Creek",
  SKIP: "Skipton",
  SLAT: "Slaty Creek",
  SMDALE: "Smythesdale",
  SMDALE: "Smythesdale",
  SMEA: "Smeaton",
  SMIT: "Smith's Creek",
  SMY: "Smythesdale",
  SMYDALE: "Smythesdale",
  SMYT: "Smith's Creek",
  SMYT: "Smythe's Creek (3)",
  SMYT: "Smythesdale",
  SNAK: "Snake Valley",
  SNAP: "Schnapper Point (2)",
  SNOW: "Snowy River",
  SNOW: "Snowy Creek",
  "SNOWY CR": "Snowy Creek",
  "SNOWY CREE": "Snowy Creek",
  "SNOWY MTN": "Snowy Mountains",
  "SO YARRA": "South Yarra",
  SOLD: "Soldier's Hill",
  SOME: "Somerton",
  SOME: "Somerset England",
  SORRE: "Sorrento",
  "SOUTH YARR": "South Yarra",
  SPEC: "Specimen Hill",
  SPEC: "Specimen Gully",
  "SPECN GLY": "Specimen Gully",
  SPOL: "Sebastopol (2)",
  SPOT: "Spotswood",
  SPRDALLAH: "Springdallah",
  SPRI: "Spring Creek (7)",
  SPRI: "Spring Hill (7)",
  SPRI: "Spring Mount (2)",
  SPRI: "Spring Vale",
  SPRI: "Springdallah",
  SPRI: "Springfield",
  SPRI: "Springhurst",
  SPRI: "Springs (3)",
  SPRI: "The Spring",
  "SPRIB BAN": "Springbank",
  "SPRIB BK": "Springbank",
  "SPRIB BNK": "Springbank",
  SPRING: "Spring Hill (7)",
  SPRING: "Spring Vale",
  "SPRING DAL": "Springdallah",
  "SPRING G": "Spring Gully (2)",
  "SPRING H": "Spring Hill (7)",
  "SPRING VAL": "Spring Vale",
  SPRINGAH: "Springdallah",
  SPRINGALLA: "Springdallah",
  SPRINGCREE: "Spring Creek (7)",
  SPRINGD: "Springdallah",
  SPRINGFIEL: "Springfield",
  SPRINGFLD: "Springfield",
  SRIDGE: "Sandridge",
  "ST A": "St Arnaud",
  "ST AN": "St Andrews",
  "ST AR": "St Arnaud",
  "ST ARND": "St Arnaud",
  "ST AW": "Stawell",
  "ST JA": "St James",
  "ST K": "St Kilda",
  "ST KI": "St Kilda",
  "ST LEON": "St Leonards On The Bay",
  "ST LEONARD": "St Leonards On The Bay",
  "ST LEONS": "St Leonards On The Bay",
  "ST UA": "Stuart Mill",
  STAF: "Staffordshire Reef",
  STAFF: "Staffordshire England",
  STAFF: "Staffordshire Vic",
  "STAFF REEF": "Staffordshire Reef",
  "STAFFORD SH": "Staffordshire Reef",
  STAG: "Staghorn Flat",
  STAN: "Stanhope",
  STAN: "Stanley",
  STAR: "St Arnaud",
  STAT: "Station Peak",
  "STATION PK": "Station Peak",
  STAW: "Stawell",
  STEE: "Steep Bank",
  STEI: "Steiglitz",
  STEIG: "Steiglitz",
  STINE: "Serpentine",
  STJA: "St James",
  STLE: "St Leonards On The Bay",
  STOC: "Stockyard Creek (3)",
  "STOCK Y HI": "Stockyard Hill",
  STOCKY: "Stockyard Creek (3)",
  "STOCKYAR H": "Stockyard Hill",
  "STOCKYD H": "Stockyard Hill",
  STOK: "Stoke-Upon-Trent UK",
  STON: "Stony Creek (4)",
  "STONY CK": "Stony Creek (4)",
  STRA: "Stratford",
  STRA: "Strathdownie",
  STRA: "Strangways",
  STRA: "Strathbogie",
  STRA: "Strathloddon",
  STRA: "Strathmore",
  STRA: "Strathfieldsaye",
  STRAFDSAY: "Strathfieldsaye",
  STRAFDYE: "Strathfieldsaye",
  STRATH: "Strathfieldsaye",
  STRATHLODD: "Strathloddon",
  STRATHSSAY: "Strathfieldsaye",
  STRE: "Streatham",
  STRI: "Stringybark Creek",
  "STRINGBK F": "Stringybark Flat",
  "STRINGY BA": "Stringybark Creek",
  STRINGYBK: "Stringybark Creek",
  STRTHBGIE: "Strathbogie",
  STUA: "Stuart Mill",
  STUD: "Studley Park",
  SUFF: "Suffolk England",
  "SUFFOLK L": "Suffolk Lead",
  "SUFFOLK LD": "Suffolk Lead",
  SUGA: "Mount Sugarloaf (2)",
  SUGA: "Sugarloaf",
  SUGA: "Sugarloaf Creek (3)",
  SULK: "Sulky Gully",
  SUNB: "Sunbury",
  SUNS: "Sunshine",
  SURR: "Surrey England",
  SURR: "Surrey River",
  SUTH: "Sutherland's Creek",
  SUTH: "Sutherland",
  SUTT: "Sutton Grange",
  "SUTTON GR": "Sutton Grange",
  SWAN: "Swan Hill",
  SWAN: "Swan Ridge",
  SWAN: "Swan Water",
  SWIF: "Swift's Creek",
  SYDN: "Sydney Road Melbourne",
  SYDN: "Sydenham",
  SYDN: "Sydney NSW",
  "TA LL": "Tallarook",
  TABI: "Tabilk",
  TABL: "Table Hill",
  TAHA: "Tahara",
  TALA: "Talangatta",
  TALB: "Talbot",
  TALBOTVILL: "Talbotville",
  TALGATTA: "Talangatta",
  TALL: "Talangatta",
  TALL: "Tallarook",
  TALL: "Tallygaroopna (Tallagaroopna)",
  TALLANGATT: "Talangatta",
  TALLAROO: "Tallarook",
  TALLYGAROO: "Tallygaroopna (Tallagaroopna)",
  TALLYGOROO: "Tallygaroopna (Tallagaroopna)",
  TAMBO: "Tambo River",
  TAMI: "Taminick",
  TANG: "Tanjil",
  TANJ: "Tanjil",
  TARA: "Taradale",
  TARAWIN: "Tarrawingee",
  TARI: "Tarilta",
  TARN: "Tarnagulla",
  TARR: "Tarrangower",
  TARR: "Tarraville",
  TARR: "Tarrawingee",
  TARR: "Tarrayoukyan",
  "TARRA SUR": "Tarra Survey",
  TARRANGOR: "Tarrangower",
  TARRAV: "Tarraville",
  TARRAWGEE: "Tarrawingee",
  TARRAYOUKY: "Tarrayoukyan",
  TARRGEE: "Tarrawingee",
  TARVILLE: "Tarraville",
  TAS: "Tasmania",
  TASM: "Tasmania",
  TATU: "Tatura",
  TATY: "Tatyoon",
  TAYL: "Taylor's Flat",
  TDALE: "Taradale",
  "TEA TR CK": "Tea-Tree Creek (3)",
  TEASD: "Teesdale",
  TEAT: "Tea-Tree Creek (3)",
  TEES: "Teesdale",
  TEMP: "Templestowe",
  TEMPLEMORE: "Templemore",
  TERA: "Terang",
  TERR: "Terrick-Terrick",
  TERRICK: "Terrick-Terrick",
  "TERRICK TE": "Terrick-Terrick",
  TGATTA: "Talangatta",
  TGON: "Traralgon",
  TGULLA: "Tarnagulla",
  "TH EL": "The Leigh",
  "THE WHIM H": "Whim Holes",
  THEL: "The Leigh",
  "THIRD WHITE": "Third White Hill",
  THOM: "Thomastown",
  THOO: "Thoona",
  THOR: "Thorpdale",
  "THR ML CK": "Three Mile Creek",
  THRE: "Three Mile Creek",
  "THREE M CK": "Three Mile Creek",
  "THREE MILE": "Three Mile Creek",
  THUR: "Thurles Co Tipperary Ireland",
  TIMB: "Lake Timboon",
  TIMB: "Timboon Creek",
  TIMO: "Timor",
  TINA: "Tinambra",
  TINT: "Tintaldra",
  TIP: "County Tipperary Ireland",
  TIPP: "County Tipperary Ireland",
  TIPP: "Tipperary Gully(4)",
  "TIPPERARY G": "Tipperary Gully(4)",
  "TIPPERARY P": "Tipperary Point (2)",
  "TIPPRY GY": "Tipperary Gully(4)",
  "TO LL": "Toolleen (Tooleen)",
  TODD: "Todd's Creek",
  TONG: "Tongala",
  TOO: "Toorak (2)",
  TOOB: "Tooboorac",
  TOOGRK: "Tootgarook",
  TOOL: "Lake Tooliorook",
  TOOL: "Toolamba (2)",
  TOOL: "Tooliorook",
  TOOL: "Toolleen (Tooleen)",
  TOOM: "Toombon",
  TOON: "Toongabbie",
  TOONG: "Toongabbie",
  TOONGAB: "Toongabbie",
  TOOR: "Toorain",
  TOOR: "Toorak (2)",
  TOOR: "Torrumbarry",
  TOOT: "Tootgarook",
  TOOTGAROO: "Tootgarook",
  TORR: "Torrumbarry",
  TORRUMBAR: "Torrumbarry",
  TOUR: "Tourello",
  TOWE: "Tower Hill (2)",
  TOWO: "Towong Shire",
  "TR H": "Tower Hill (2)",
  TRAF: "Trafalgar",
  TRAR: "Traralgon",
  TRAW: "Trawalla",
  TREN: "Trentham Diggings",
  TREN: "Trentham East",
  TREW: "Trewalla",
  TRUG: "Truganina",
  TRUG: "Truganina Swamps",
  TSTOWE: "Templestowe",
  TULL: "Tullarmarine",
  TULLAMA: "Tullarmarine",
  TULLAMARIN: "Tullarmarine",
  TULLRINE: "Tullarmarine",
  TUNG: "Tungamah",
  TVILLE: "Tarraville",
  TWOM: "Two Mile Creek",
  TYAB: "Tyabb",
  TYER: "Lake Tyers",
  TYLD: "Tylden",
  TYRE: "Tyrendarra",
  TYRO: "County Tyrone Ireland",
  TYRR: "Tyrendarra",
  ULLI: "Ullina",
  ULUP: "Ulupna West",
  UNDE: "Undera",
  "UNWINS S": "Unwin's Special Survey",
  "UNWINS S": "Unwin's Special Survey",
  "UNWINS SUR": "Unwin's Special Survey",
  "UP PLENTY": "Upper Plenty",
  UPPE: "Upper Plenty",
  "UPPER BUCK": "Upper Buckland",
  "UPPER DARG": "Upper Dargo",
  "UPPER MACE": "Upper Macedon",
  "UPPER MAFF": "Upper Maffra",
  "UPPER PL": "Upper Plenty",
  "UPPER PLEN": "Upper Plenty",
  "UPPER PLY": "Upper Plenty",
  "UPPER YARR": "Upper Yarra",
  VAUG: "Vaughan",
  VDL: "Van Dieman's Land (Tasmania)",
  "VI TOWN": "Violet Town",
  VIAD: "Viaduct Township",
  VICT: "Victoria",
  VICT: "Victoria Gully",
  "VICTORIA G": "Victoria Gully",
  VIOL: "Violet River",
  VIOL: "Violet Town",
  "VIOLET CR": "Violet Creek",
  "VIOLET PND": "Violet Ponds",
  "VIOLET T": "Violet Town",
  "VIOLET TOW": "Violet Town",
  "VIOLET TWN": "Violet Town",
  "VITE-VITE": "Mount Vite-Vite",
  "W WALLAN": "Wallan-Wallan",
  "W YALLOCK": "Wandin Yalloak",
  WAAN: "Waanyarra",
  WABD: "Wabdallah",
  "WAHA (sp)": "Walhalla",
  WAHG: "Wahgunyah",
  WAHR: "Wahring",
  WAHYAH: "Wahgunyah",
  WALH: "Walhalla",
  WALL: "Wallan-Wallan",
  WALLAN: "Wallan-Wallan",
  "WALLAN W": "Wallan-Wallan",
  "WALLAN WAL": "Wallan-Wallan",
  "WALLAN WN": "Wallan-Wallan",
  WALM: "Walmer",
  WALS: "Wales UK",
  WAND: "Wandilgong",
  WAND: "Wando Vale",
  WAND: "Wandong",
  WANDGONG: "Wandilgong",
  WANDIGONG: "Wandilgong",
  "WANDIN YALL": "Wandin Yalloak",
  "WANDY YALL": "Wandin Yalloak",
  "WANDY YALL": "Wandin Yalloak",
  WANG: "Wangaratta",
  WANG: "Wangoom",
  WANGATTA: "Wangaratta",
  WANGOO: "Wangoom",
  WANGT: "Wangaratta",
  WANGTTA: "Wangaratta",
  WANN: "Wannon Shire",
  WARA: "Waranga",
  WARB: "Warburton (2)",
  WARB: "Warrnambool",
  WARBOOL: "Warrnambool",
  "WARD(sp)": "Wandin Yalloak",
  WARE: "Wareek",
  WARNABOOL: "Warrnambool",
  WARR: "Warburton (2)",
  WARR: "Warragul",
  WARR: "Warrambine Creek",
  WARR: "Warrak",
  WARR: "Warrong",
  WARR: "Warrayure",
  WARR: "Warrenheip",
  WARR: "Warrnambool",
  WARRACK: "Warracknabeal",
  "WARRACK BE": "Warracknabeal",
  WARRACKNA: "Warracknabeal",
  WARRNAMBOO: "Warrnambool",
  WATC: "Watch Hill",
  WATE: "Waterloo(3)",
  WATG: "Watgania",
  WATS: "Watson's Creek (2)",
  WATT: "Wattle Flat",
  WATTA: "Wangaratta",
  WAUR: "Waurn Ponds (2)",
  WBEAL: "Warracknabeal",
  WBEAL: "Werracknabeal",
  WBEE: "Werribee",
  WBIRCHIP: "Wirrumbirchip",
  WBOOL: "Warrnambool",
  WBURN: "Wedderburn",
  WDYTE: "Warrandyte",
  WEAT: "Weatherboard Hill",
  WEDD: "Wedderburn",
  WEHL: "Wehla",
  WELL: "Wellington",
  "WELLTN GY": "Wellington Gully",
  WELS: "Welshman's Reef",
  WELSH: "Welshman's Reef",
  WELSHMS: "Welshman's Reef",
  "WELTON G": "Wellington Gully",
  WEND: "Wendouree",
  WENS: "Wensleydale",
  WERR: "Werracknabeal",
  WERR: "Werribee",
  WERRAC: "Werracknabeal",
  WERRACKNAB: "Werracknabeal",
  WEST: "Western Port",
  "WESTERN P": "Western Port",
  "WESTN PORT": "Western Port",
  WEXF: "County Wexford Ireland",
  WGOOM: "Wangoom",
  WGUL: "Warragul",
  "WH H": "White Hills (Bendigo)",
  "WH IT": "White Hills (Bendigo)",
  WHALLA: "Walhalla",
  WHAR: "Wharparilla",
  WHEA: "Wheat Land",
  WHEIP: "Warrenheip",
  WHILLS: "White Hills (Bendigo)",
  WHIM: "Whim Holes",
  WHIP: "Whipstick Diggings",
  WHIT: "White Hills (Bendigo)",
  WHIT: "Whittlesea",
  WHITE: "White Hills (Bendigo)",
  "WHITE H": "White Hills (Bendigo)",
  WHITSEA: "Whittlesea",
  WHOR: "Whorouly",
  WHRO: "Whroo",
  WHSEA: "Whittlesea",
  WICK: "Co Wicklow Ireland",
  WICK: "Wickliffe",
  WICK: "Wickliffe Road",
  WILD: "Wild-Duck Creek(2)",
  WILD: "Wilderness",
  WILL: "Williamstown",
  WILLMTOWN: "Williamstown",
  "WILLO MAVI": "Willowmavin",
  WILLOWHAVI: "Willowmavin",
  "WILLOW-M": "Willowmavin",
  WILLOWMAVN: "Willowmavin",
  WILLSTOWN: "Williamstown",
  WILLTN: "Williamstown",
  WILS: "Williamstown",
  WIMM: "Wimmera",
  WINC: "Winchelsea",
  WIND: "Windermere",
  WIND: "Windsor",
  WIND: "Windsor NSW",
  WIND: "Windsor Engl",
  WINS: "Winslow",
  WINSEA: "Winchelsea",
  WINT: "Winton",
  WINT: "Winter's Flat",
  WIRR: "Wirrumbirchip",
  WITCHIPOO: "Witchipool",
  "WM TOWN": "Williamstown",
  "WM WALLAN": "Wallan-Wallan",
  "WMS TOWN": "Williamstown",
  WNABEAL: "Werracknabeal",
  WOAD: "Woady Yalloak Creek",
  "WOADY YALL": "Woady Yalloak Creek",
  WODO: "Wodonga",
  WOMB: "Wombat Flats",
  WOMB: "Wombat Creek (4)",
  WOMBAT: "Wombat Flats",
  WOMBAT: "Wombat Creek (4)",
  WONW: "Wonwanda",
  WOOD: "Woodford",
  WOOD: "Woodstock (2)",
  WOOD: "Woodend",
  WOOD: "Woods Point",
  WOOD: "Woodlands",
  WOOL: "Wollert",
  WOOL: "Woolshed Creek(2)",
  WOOL: "Woolbrook",
  WOOL: "Woolshed",
  WOOL: "Woolsthorpe",
  WOOLSTHOR: "Woolsthorpe",
  WOOR: "Woorndoo",
  WOOR: "Wooroonoke",
  WOOR: "Wooragee",
  WOORAK: "Woori Yalloak",
  WORA: "Woranga",
  "WORA (sp)": "Waranga",
  WORD: "Wurdiboluc",
  WORM: "Wormbete Creek",
  WPROOF: "Wycheproof",
  WSEA: "Whittlesea",
  "W'SEA": "Winchelsea",
  WSOR: "Windsor",
  "WST PORT": "Western Port",
  "WSTICK DG": "Whipstick Diggings",
  WTOWN: "Williamstown",
  WURD: "Lake Wurdee-Boluc",
  WURD: "Wurdiboluc",
  "WURDEE BOL": "Lake Wurdee-Boluc",
  "WURDEE BOL": "Wurdiboluc",
  WYCH: "Wycheproof",
  WYCH: "Wychetella",
  WYND: "Wyndham",
  WYUN: "Wyuna",
  "Y GLEN": "Yarra Glen",
  YACK: "Yackandandah",
  YACKANDAH: "Yackandandah",
  YACKANDAND: "Yackandandah",
  YALL: "Yalloak",
  YALLO: "Yalloak",
  YAM: "Yambuk",
  YAMB: "Yambuk",
  YAND: "Yando",
  YAND: "Yandoit",
  YANG: "Yangery",
  YANG: "Yangery Creek",
  YANY: "Yan Yean",
  YAPE: "Yapeen",
  YARP: "Yarpturk",
  YARR: "Yarra Bend",
  YARR: "Yarra Falls",
  YARR: "Yarra Flats",
  YARR: "Yarraberg",
  YARR: "Yarragon",
  YARR: "Yarram",
  YARR: "Yarraville",
  YARR: "Yarraweya",
  YARR: "Yarrawonga",
  YARR: "Yarrum-Yarrum",
  "YARRA B": "Yarra Bend",
  "YARRA FL": "Yarra Flats",
  "YARRA SURV": "Yarra Survey",
  "YARRA YARR": "Yarrum-Yarrum",
  "YARRAM Y": "Yarrum-Yarrum",
  "YARRAM YAR": "Yarrum-Yarrum",
  "YARRUM YM": "Yarrum-Yarrum",
  YAWO: "Yawong",
  YDAH: "Yackandandah",
  YDANDAH: "Yackandandah",
  YELI: "Yelima Creek",
  YEND: "Yendon",
  YERI: "Yering",
  YIELI: "Yielima",
  YONGA: "Yarrawonga",
  YOUA: "Youanmite",
  YOUA: "Youarang",
  YOUANGS: "You-Yangs",
  YOWE: "Yowen Hill",
  YUPP: "Yuppeckiar Creek",
  YVILLE: "Yarraville",
  YWONGA: "Yarrawonga",
};

function expandVictoriaAbbreviations(placeString) {
  // For now this is disabled
  // The data is too ambigous
  return placeString;

  if (!placeString) {
    return placeString;
  }

  let abbrevName = placeString;
  let firstCommaIndex = placeString.indexOf(",");
  if (firstCommaIndex != -1) {
    abbrevName = placeString.substring(0, firstCommaIndex).trim();
  }

  let mappedName = abbreviationTable[abbrevName];
  if (mappedName) {
    if (firstCommaIndex != -1) {
      let remainder = placeString.substring(firstCommaIndex + 1).trim();
      return mappedName + ", " + remainder;
    } else {
      return mappedName + ", Australia";
    }
  } else {
    return placeString;
  }
}

export { expandVictoriaAbbreviations, vicbdmPlaceAbbreviationTable };
